In [2]:
import numpy as np

# 10 zeros

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 10 uns

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# 10 cincos

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# 10 ate 50

In [6]:
np.arange(10, 51, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# pares de 10 ate 50

In [7]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# 3x3 0 ate 8

In [8]:
np.arange(0, 9, 1).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 3x3 Identidade

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Rand

In [36]:
np.random.rand(1)

array([0.89845686])

# Rand distribuição normal

In [39]:
np.random.randn(5,5)

array([[-1.7904601 ,  0.18307503, -1.24352025, -0.50735105, -0.1206645 ],
       [-0.01258339, -0.83198422, -0.68622162,  0.78211628,  1.06431307],
       [-0.77825455, -0.3906471 ,  0.09026003, -0.03454831, -0.00848505],
       [ 0.03490716,  0.23200724, -0.68560812,  0.63887803,  1.45581593],
       [ 1.2851953 , -0.60983444,  1.60760176,  0.38252624,  1.02434631]])

# 0 -> 1 de 0.01 

In [12]:
np.linspace(0.01, 1, 100).reshape((10, 10))

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# 0->1 20 numeros

In [13]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Outros exemplos

In [26]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [24]:
mat[3,4]

20

In [37]:
mat[:3, 1].reshape(3, -1)

array([[ 2],
       [ 7],
       [12]])

In [39]:
mat[mat>20]

array([21, 22, 23, 24, 25])

In [40]:
mat[mat>15].reshape(2, -1)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Operações

In [41]:
mat.sum()

325

In [42]:
mat.std()

7.211102550927978

In [43]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])